services:
  - docker

os: linux

dist: focal

language: go

go:
  - 1.17.x

branches:
  only:
    - master

before_script:
  - source dev/env_develop
  - make start_dependencies
  - sleep 15

script:
  - make test
  - make build

after_script:
  - make rm_dependencies

notifications:
  email:
    - bifer@alea-soluciones.com
