
language: go
go:
 - 1.5
 - 1.6
 - tip

sudo: false

before_install:
  - go get -v ./...
  - go get github.com/stretchr/testify/assert
  - go get -u github.com/golang/lint/golint

services:
  - rabbitmq

env:
 - AMQP_URL=amqp://guest:guest@127.0.0.1:5672/ MYSQL_URL=mysql://root:@127.0.0.1:3306/test

before_script:
  - mysql -e 'create database test;'

script:
  - make all
  - cd example; go build example.go
