
language: go
go:
 - 1.3
 - 1.4
 - tip

before_install:
  - go get -v ./...
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover


services:
  - rabbitmq

env:
 - AMQP_URL=amqp://guest:guest@127.0.0.1:5672/

script:
  - go build
  - go test -tags integration ./...
  - $HOME/gopath/bin/goveralls -repotoken 3AS6K6bjImhYrxzQNg2lczOVjkjKneEGv
