
language: go
go:
 - 1.3
 - 1.4
 - tip

before_install:
  - go get -v ./...

services:
  - rabbitmq

env:
 - AMQP_URL=amqp://guest:guest@127.0.0.1:5672/

script:
  - go build
  - cd example; go build example.go
  - go test -tags integration ./...
