sudo: required

language: go
go:
 - 1.5
 - 1.6
 - tip


sudo: false

services:
  - docker

env:
 - AMQP_URL=amqp://guest:guest@127.0.0.1:5673/ MYSQL_URL=mysql://root:@localhost:3307/mysql POSTGRES_URL=postgres://postgres:mysecretpassword@localhost:5433/postgres?sslmode=disable

before_script:
  - docker run -p 3307:3306 --name mysql -e MYSQL_ROOT_PASSWORD=rootpass -d mysql
  - docker run -p 5433:5432 --name postgres -e POSTGRES_PASSWORD=mysecretpassword -d postgres:9.5
  - docker run -p 5673:5672 --name rabbitmq -d rabbitmq

after_script:
  - docker stop mysql
  - docker rm mysql
  - docker stop postgres
  - docker rm postgres
  - docker stop rabbitmq
  - docker rm rabbitmq

script:
  - make all
  - cd example; go build example.go
