name: ci

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      BROKER_URI: amqp://guest:guest@localhost:5664/
      POSTGRES_URI: postgres://postgres:postgres@localhost:3314/postgres?sslmode=disable
      MYSQL_URI: mysql://postgres:postgres@localhost:5404/postgres

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.17
      
      - name: Source
        run: | 
          source dev/env_develop
          make start_dependencies
          sleep 15

      - name: Build
        run: make build

      - name: Test
        run: make test
